version: '3.8'

services:
  api:
    build: ./backendset
    container_name: inotes-api
    ports:
      - "5500:5500"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - inotes-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: inotes-client
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./client/src:/app/src
    restart: unless-stopped
    networks:
      - inotes-network
    depends_on:
      - api

networks:
  inotes-network:
    driver: bridge
