services:
<<<<<<< HEAD

=======
>>>>>>> 57c331d (Add Docker Compose setup for frontend and backend)
  backend:
    build:
      context: ./backendset
    container_name: inotes-backend
    ports:
      - "5500:5500"
    env_file:
      - .env

  frontend:
    build:
      context: ./client
    container_name: inotes-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
<<<<<<< HEAD
=======
    environment:
      - PORT=3000
>>>>>>> 57c331d (Add Docker Compose setup for frontend and backend)
    depends_on:
      - backend
